import { WeaponDefinition } from '../types';

export const bunkerBusterWeapon: WeaponDefinition = {
  id: 'bunker_buster',
  name: 'Bunker Buster',
  category: 'AIR_SUPPORT',
  behavior: 'BUNKER_BUSTER',
  icon: '🕳️',
  description: 'Bombe perforante guidée qui traverse et creuse un puits dans le sol avant d\'exploser en profondeur.',
  damage: 60,
  radius: 45,
  defaultAmmo: 1,
  turnDelay: 1,
  crateProbability: 0.15,
  windAffected: false,
  bounces: false,
  requiresTarget: true,
  craftable: true,
  chargeable: false,
  triggersRetreat: true,
  customSoundKey: 'siren',
  createProjectiles: () => [],
};

export const mineStrikeWeapon: WeaponDefinition = {
  id: 'mine_strike',
  name: 'Frappe de Mines',
  category: 'AIR_SUPPORT',
  behavior: 'MINE_STRIKE',
  icon: '💣',
  description: 'Largage aérien de 5 mines terrestres actives réparties au-dessus de la zone ciblée.',
  damage: 45,
  radius: 35,
  defaultAmmo: 1,
  turnDelay: 2,
  crateProbability: 0.10,
  windAffected: false,
  bounces: true,
  requiresTarget: true,
  craftable: true,
  chargeable: false,
  triggersRetreat: true,
  customSoundKey: 'siren',
  createProjectiles: () => [],
};

export const kamikazeWeapon: WeaponDefinition = {
  id: 'kamikaze',
  name: 'Kamikaze',
  category: 'SPECIAL',
  behavior: 'KAMIKAZE',
  icon: '🚀',
  description: 'Propulse la limace en ligne droite à pleine vitesse pour perforer le décor avant d\'exploser héroïquement !',
  damage: 60,
  radius: 50,
  defaultAmmo: 1,
  turnDelay: 0,
  crateProbability: 0.10,
  windAffected: false,
  bounces: false,
  craftable: true,
  chargeable: false,
  triggersRetreat: true,
  customSoundKey: 'fire',
  createProjectiles: () => [],
};
