import { WeaponDefinition } from '../types';
import { ActiveProjectile } from '../../types';

export const ninjaRopeWeapon: WeaponDefinition = {
  id: 'ninja_rope',
  name: 'Corde Ninja',
  category: 'UTILITY',
  behavior: 'NINJA_ROPE',
  icon: '🪢',
  description: 'Tirez un grappin pour vous balancer à travers la carte, grimper et larguer des armes en vol.',
  damage: 0,
  radius: 0,
  defaultAmmo: -1,
  turnDelay: 0,
  crateProbability: 0,
  windAffected: false,
  bounces: false,
  craftable: true,
  chargeable: false,
  customSoundKey: 'rope_shoot',
  createProjectiles: () => [],
};

export const girderWeapon: WeaponDefinition = {
  id: 'girder',
  name: 'Poutre Métallique',
  category: 'UTILITY',
  behavior: 'GIRDER',
  icon: '🪜',
  description: 'Placez une poutre en acier orientable pour créer un pont au-dessus du vide ou un bouclier.',
  damage: 0,
  radius: 0,
  defaultAmmo: 3,
  turnDelay: 0,
  crateProbability: 0.20,
  windAffected: false,
  bounces: false,
  craftable: true,
  chargeable: false,
  hideReticle: true,
  requiresTarget: true,
  customSoundKey: 'girder',
  createProjectiles: () => [],
};

export const airdropWeapon: WeaponDefinition = {
  id: 'airdrop',
  name: 'Caisse de Ravitaillement',
  category: 'UTILITY',
  behavior: 'AIRDROP',
  icon: '📦',
  description: 'Largage aérien d\'une caisse en parachute qui soigne +50 HP à la première limace qui la touche.',
  damage: 0,
  radius: 0,
  defaultAmmo: 2,
  turnDelay: 0,
  crateProbability: 0.15,
  windAffected: true,
  bounces: false,
  craftable: true,
  chargeable: false,
  requiresTarget: true,
  customSoundKey: 'airdrop',
  createProjectiles: () => [],
};

export const jetpackWeapon: WeaponDefinition = {
  id: 'jetpack',
  name: 'Jetpack',
  category: 'UTILITY',
  behavior: 'JETPACK',
  icon: '🎒',
  description: 'Vol dorsal propulsé avec 5 secondes de carburant actif. Contrôles aux touches de saut et direction.',
  damage: 0,
  radius: 0,
  defaultAmmo: 1,
  turnDelay: 0,
  crateProbability: 0.15,
  windAffected: false,
  bounces: false,
  craftable: true,
  chargeable: false,
  hideReticle: true,
  customSoundKey: 'jetpack',
  createProjectiles: () => [],
};

export const pneumaticDrillWeapon: WeaponDefinition = {
  id: 'pneumatic_drill',
  name: 'Marteau-Piqueur',
  category: 'UTILITY',
  behavior: 'DRILL',
  icon: '🔨',
  description: 'Creuse verticalement un puits tubulaire sous vos pieds dans la roche (20 dégâts aux ennemis traversés).',
  damage: 20,
  radius: 14,
  defaultAmmo: 1,
  turnDelay: 0,
  crateProbability: 0.15,
  windAffected: false,
  bounces: false,
  craftable: true,
  chargeable: false,
  hideReticle: true,
  customSoundKey: 'drill',
  createProjectiles: () => [],
};

export const parachuteWeapon: WeaponDefinition = {
  id: 'parachute',
  name: 'Parachute',
  category: 'UTILITY',
  behavior: 'PARACHUTE',
  icon: '🪂',
  description: 'Déploie un parachute en l\'air pour freiner la chute, planer avec le vent et annuler les dégâts de chute.',
  damage: 0,
  radius: 0,
  defaultAmmo: -1,
  turnDelay: 0,
  crateProbability: 0,
  windAffected: true,
  bounces: false,
  craftable: true,
  chargeable: false,
  hideReticle: true,
  customSoundKey: 'parachute',
  createProjectiles: () => [],
};

export const magnetWeapon: WeaponDefinition = {
  id: 'magnet',
  name: 'Aimant',
  category: 'UTILITY',
  behavior: 'BOUNCING_TIMER',
  icon: '🧲',
  description: 'Électroaimant à lancer comme une grenade. Règle la polarité (1 = Attirer 🔵, 2 = Repousser 🔴) avant de lancer. Actif 3 tours sur le terrain.',
  damage: 0,
  radius: 250,
  defaultAmmo: 1,
  turnDelay: 1,
  crateProbability: 0.12,
  windAffected: false,
  bounces: true,
  fuseTimeMs: 2500,
  allowCustomFuse: true,
  craftable: true,
  chargeable: true,
  triggersRetreat: true,
  customSoundKey: 'grenade_throw',
  createProjectiles: (ctx) => {
    const rad = (ctx.angleDeg * Math.PI) / 180;
    const speed = (ctx.power / 100) * 14 + 3;
    const isRepel = ctx.fuseTimerMs !== undefined && ctx.fuseTimerMs === 2000;
    const polarity: 'ATTRACT' | 'REPEL' = isRepel ? 'REPEL' : 'ATTRACT';
    return [
      {
        id: `proj_${Date.now()}_${Math.random()}`,
        weaponId: 'magnet',
        x: ctx.originX,
        y: ctx.originY,
        vx: Math.cos(rad) * speed,
        vy: Math.sin(rad) * speed,
        radius: 6,
        fuseTimerMs: 2500,
        bounces: true,
        windAffected: false,
        ownerSlugId: ctx.ownerSlugId,
        behaviorData: { isMagnetDeployable: true, polarity },
      },
    ];
  },
};

export const skipTurnWeapon: WeaponDefinition = {
  id: 'skip_turn',
  name: 'Passer son tour',
  category: 'UTILITY',
  behavior: 'SKIP_TURN',
  icon: '🏳️',
  description: 'Passe immédiatement la main à l\'équipe suivante sans utiliser d\'action.',
  damage: 0,
  radius: 0,
  defaultAmmo: -1,
  turnDelay: 0,
  crateProbability: 0,
  windAffected: false,
  bounces: false,
  craftable: true,
  chargeable: false,
  hideReticle: true,
  customSoundKey: 'tick',
  createProjectiles: () => [],
};


